version: '3.8'
services:
  # Front End Page Server (Monitor)
  front-end-server:
    image: elven9/lab-monitor:latest
    environment: 
      - PORT=${FRONT_END_PORT:-3000}

  # Grafana
  grafana:
    image: grafana/grafana
    volumes:
      - type: volume
        source: grafana-storage
        target: /var/lib/grafana
    environment:
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=https://localhost:3000/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
  
  # Api Server
  api-server:
    image: elven9/lab-backend:latest
    volumes: 
      - type: bind
        source: /etc/kubernetes/admin.conf
        target: /root/.kube/config
    # command: [ "-escapeCheck=true" ]

  # Nginx Reverse Proxy Server
  nginx-reverse-proxy-server:
    image: nginx
    ports: 
      - "8080:8080"
    volumes: 
      - ${DOCKER_COMPOSE_PWD}/nginx-reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - "front-end-server"
      - "grafana"
      - "api-server"

  # Prometheus Server Port Fowarding
  prometheus-port-fowarding:
    image: bitnami/kubectl
    volumes: 
      - type: bind
        source: ~/.kube/config
        target: /.kube/config
    command: ["--namespace", "monitoring", "port-forward", "svc/prometheus-k8s", "9090"]
    ports: 
      - "9090:9090"

volumes: 
  grafana-storage: