apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: cpu2
spec:
  max-instances: 4
  min-instances: 1
  cleanPodPolicy: "All"
  tfReplicaSpecs:
    PS:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          terminationGracePeriodSeconds: 0
          containers:
          - args:
            #- 'sleep 99d'
            - 'curl -s http://140.114.78.229/web/mnist-new.py | python3 -'
            env:
            - name: global_steps
              value: "100000"
            command:
            - /bin/bash
            - -c
            image: ncy9371/tensorflow:1.15.2-py3-noavx
            name: tensorflow
            ports:
            - containerPort: 2222
              name: tfjob-port
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          terminationGracePeriodSeconds: 0
          containers:
          - args:
            #- 'sleep 99d'
            - 'curl -s http://140.114.78.229/web/mnist-new.py | python3 -'
            env:
            - name: global_steps
              value: "100000"
            command:
            - /bin/bash
            - -c
            image: ncy9371/tensorflow:1.15.2-py3-noavx
            name: tensorflow
            ports:
            - containerPort: 2222
              name: tfjob-port
            resources:
              requests:
                cpu: "4"
                memory: "4Gi"
