{
 "title": "Single Job Panel",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "jobName", "label": "Job Name" }
  ]
 },
 "panels": [
  {
   "title": "TFJob Cpu Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"default\", pod=~\"^[[jobName]]-(worker|ps)-\\\\d\", resource=\"cpu\"})",
     "legendFormat": "Cpu Usage (cores)"
    }
   ]
  },
  {
   "title": "TFJob Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"^[[jobName]]-(worker|ps)-\\\\d\"})",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Worker Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=~\"default\", pod=~\"^[[jobName]]-worker-\\\\d\"})",
     "legendFormat": "Worker(s)"
    }
   ]
  },
  {
   "title": "Parameter Server Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=~\"default\", pod=~\"^[[jobName]]-ps-\\\\d\"})",
     "legendFormat": "Parameter Server(s)"
    }
   ]
  }
 ]
}